### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by tomyan112** [hojatsajadinia/AndRoPass#1]
![image](https://github.com/koengu/AndRoPass/assets/9064351/6e4b987b-3a00-4917-93a5-6c19bd1ff40c)

I have place utils,.gitignore, AndRoPass.py, LICENSE, README, md, requirements.txt and the apk  file in the python directory. Then I ran python AndRoPass.py -a taobao.apk

File not found error appeared.

**Comment by hojatsajadinia** [comment]
Dear tomyan112,
I have made some major changes to the AndRoPass. Please try again and let me know if you encounter any errors.

**Comment by hojatsajadinia** [comment]
Dear tomyan112,
I have made some major changes to the AndRoPass. Please try again and let me know if you encounter any errors.
