### ISSUE TITLE
App still detecting root / emulator

### ISSUE THREAD

**Issue by hrylx** [hojatsajadinia/AndRoPass#5]
App:
de.payback.android.client -> https://www.apkmirror.com/apk/payback/payback-deutschlands-grostes-bonusprogramm/

OS tested:
Android 7, 8, 9, 10, 11

Until version 23.02.2100 the app ran fine, without any noticeable anti root / emulator stuff. 
Every version after that does not run anymore on Android Studio Emulator.  Would be most interested in version from 24.01.1800 forward (new API)

Edit: Also, what is the Difference between WR and WOR Apks?

**Comment by Assia55** [comment]
UP

**Comment by hojatsajadinia** [comment]
Hi @hrylx,

The application you mentioned appears to have tamper detection and verifies the app's signature. Therefore, you won't be able to use AndRoPass until you bypass the tamper detection mechanism.
