### ISSUE TITLE
Apk file not found

### ISSUE THREAD

**Issue by dsymonds92** [hojatsajadinia/AndRoPass#6]
Have spent weeks trying to figure this out but whatever I do I get [error] APK file not found

**Comment by hojatsajadinia** [comment]
Hi @dsymonds92,

I have tested the latest version on both Windows 11 and Ubuntu 22.04 (WSL) and did not encounter the "APK file not found" error. Could you please provide more details about the issue? Specifically, which command did you execute?

Here are the commands I used for testing:

Windows:
```
python .\AndRoPass.py -a Sample.apk
python .\AndRoPass.py -a "C:\Users\hojat\Downloads\Sample.apk"
```

Ubuntu:
```
python3 AndRoPass.py -a "/mnt/c/Users/Hojat/Documents/AndRoPass/Sample.apk"
python3 AndRoPass.py -a Sample.apk
```

Please ensure that your command is correct and matches one of the examples above.
