### ISSUE TITLE
WR & WOR

### ISSUE THREAD

**Issue by Assia55** [hojatsajadinia/AndRoPass#7]
I'm curious about the difference between the two output APK files. One is labeled 'WR' and the other 'WOR'. Could you explain what sets them apart

**Comment by Assia55** [comment]
UP

**Comment by 6fingerfist** [comment]
With Resources/Without Resources

**Comment by Assia55** [comment]
Which one do you recommend to use ? ( WR or WOR )

**Comment by 6fingerfist** [comment]
Well if you have the resources for your phone go with wr and if you don't
go wor.

**Comment by Assia55** [comment]
@6fingerfist what mean resources ? can u explain more , pLease :D

**Comment by hojatsajadinia** [comment]
Hi, @6fingerfist @Assia55 

Thanks for using AndRoPass :)
When decompiling an Android application, you need to handle two components: the source code (Java files) and the resources (images, XML files, etc.). Sometimes, decompiling and recompiling an application with the resources can lead to runtime errors.

If you encounter errors with one version of AndRoPass's output (WR or WOR), you can try using a different output from AndRoPass. The outputs are identical except for the way they handle resource decompilation, and there are no additional recommendations or differences between them.
