### ISSUE TITLE
Issue: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 149: invalid continuation byte

### ISSUE THREAD

**Issue by Yergali2007** [hojatsajadinia/AndRoPass#8]
Tried the tool on a apk of a game called Matr1x Fire. but it returned this error. Full log:
[INFO] Checking AndRoPass requirements
[INFO] Java binary found:  "1.8.0_391"
[INFO] APKTool binary found
[INFO] Uber Apk Signer binary found
[INFO] Decompiling applicaiton
Traceback (most recent call last):
  File "C:\Users\****\Downloads\AndRoPass-v0.1\AndRoPass-v0.1\AndRoPass.py", line 73, in <module>
    main()
  File "C:\Users\****\Downloads\AndRoPass-v0.1\AndRoPass-v0.1\AndRoPass.py", line 48, in main
    if not compiler.decompile():
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\Downloads\AndRoPass-v0.1\AndRoPass-v0.1\utils\Compiler.py", line 51, in decompile
    decompile_with_res_status = self.check_for_exception(stdout.decode('utf-8'))
                                                         ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 149: invalid continuation byte

**Comment by hojatsajadinia** [comment]
Hi Yergali2007,

Thank you so much for reporting this bug and helping us improve the project. Your feedback is invaluable.

We have made some changes and believe the issue has been resolved. Could you please test again and let us know if the problem persists?

Best regards,
